SiteAquario/Controllers/GraficoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiteAquario.Controllers
{
    public class GraficoController : Controller
    {
        public IActionResult Grafico()
        {
            return View();
        }
    }
}

SiteAquario/Controllers/TelaTemperaturaController.cs
using Microsoft.AspNetCore.Mvc;
using SiteAquario.Data;
using SiteAquario.Models;
using Microsoft.EntityFrameworkCore;
using SiteAquario.Hubs; 
using Microsoft.AspNetCore.SignalR;

namespace SiteAquario.Controllers
{
    //[Route("api/[controller]")]
    //[ApiController]

    public class TelaTemperaturaController : Controller
    {
        private readonly SiteAquarioContext _context;

        public TelaTemperaturaController(SiteAquarioContext context, IHubContext<SensorHub> hubContext)
        {
            _context = context;
        }

        [HttpGet("ValoresSensor/TemperaturaHistorico")]
        public async Task<IActionResult> TemperaturaHistorico()
        {
            var historico = await _context.ValoresSensor
               .OrderBy(v => v.DataCadastro)
               .Select(v => new { v.Temperatura, v.DataCadastro })
               .ToListAsync();
            return Ok(historico);
        }

        [HttpGet("ValoresSensor/PhHistorico")]
        public async Task<IActionResult> PhHistorico()
        {
            var historico = await _context.ValoresSensor
               .OrderBy(v => v.DataCadastro)
               .Select(v => new { v.Ph, v.DataCadastro })
               .ToListAsync();
            return Ok(historico);
        }

        [HttpGet("ValoresSensor/Temperatura")]
        public IActionResult Temperatura()
        {
            return View();
        }

        [HttpGet("ValoresSensor/Ph")]
        public IActionResult Ph()
        {
            return View();
        }
    }
}

SiteAquario/Controllers/ValoresSensorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using SiteAquario.Data;
using SiteAquario.Hubs;
using SiteAquario.Models;

namespace SiteAquario.Controllers
{
    public class ValoresSensorController : Controller
    {

        private readonly SiteAquarioContext _context;
        private readonly IHubContext<SensorHub> _hubContext;

        public ValoresSensorController(SiteAquarioContext context, IHubContext<SensorHub> hubContext)
        {
            _context = context;
            _hubContext = hubContext;
        }


        [HttpPost("ReceiveData")]
        [HttpGet("ValoresSensor/ReceiveData")]
        public async Task<IActionResult> ReceiveData([FromQuery] double temperature, [FromQuery] double ph)
        {

            var valoresSensor = new ValoresSensor
            {
                Temperatura = temperature,
                Ph = ph,
                DataCadastro = DateTime.Now
            };
            _context.ValoresSensor.Add(valoresSensor);
            await _context.SaveChangesAsync();
            await _hubContext.Clients.All.SendAsync("ReceiveSensorData", valoresSensor);

            return Ok(valoresSensor);
        }

        // GET: ValoresSensor
        public async Task<IActionResult> Index()
        {
              return _context.ValoresSensor != null ? 
                          View(await _context.ValoresSensor.ToListAsync()) :
                          Problem("Entity set 'Contexto.ValoresSensor'  is null.");
        }

        // GET: ValoresSensor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ValoresSensor == null)
            {
                return NotFound();
            }

            var valoresSensor = await _context.ValoresSensor
                .FirstOrDefaultAsync(m => m.ValoresSensorID == id);
            if (valoresSensor == null)
            {
                return NotFound();
            }

            return View(valoresSensor);
        }

        // GET: ValoresSensor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ValoresSensor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ValoresSensorID,Ph,Temperatura,DataCadastro")] ValoresSensor valoresSensor)
        {
            if (ModelState.IsValid)
            {
                valoresSensor.DataCadastro = DateTime.Now;
                _context.Add(valoresSensor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(valoresSensor);
        }

        // GET: ValoresSensor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ValoresSensor == null)
            {
                return NotFound();
            }

            var valoresSensor = await _context.ValoresSensor.FindAsync(id);
            if (valoresSensor == null)
            {
                return NotFound();
            }
            return View(valoresSensor);
        }

        // POST: ValoresSensor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ValoresSensorID,Ph,Temperatura,DataCadastro")] ValoresSensor valoresSensor)
        {
            if (id != valoresSensor.ValoresSensorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(valoresSensor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ValoresSensorExists(valoresSensor.ValoresSensorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(valoresSensor);
        }

        // GET: ValoresSensor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ValoresSensor == null)
            {
                return NotFound();
            }

            var valoresSensor = await _context.ValoresSensor
                .FirstOrDefaultAsync(m => m.ValoresSensorID == id);
            if (valoresSensor == null)
            {
                return NotFound();
            }

            return View(valoresSensor);
        }

        // POST: ValoresSensor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ValoresSensor == null)
            {
                return Problem("Entity set 'Contexto.ValoresSensor'  is null.");
            }
            var valoresSensor = await _context.ValoresSensor.FindAsync(id);
            if (valoresSensor != null)
            {
                _context.ValoresSensor.Remove(valoresSensor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ValoresSensorExists(int id)
        {
          return (_context.ValoresSensor?.Any(e => e.ValoresSensorID == id)).GetValueOrDefault();
        }
    }
}

SiteAquario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteAquario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SiteAquario.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    <link rel="stylesheet" href="~/css/fontawesome.min.css" />
    <link rel="stylesheet" href="/css/styles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Sistema Aquarium</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="TelaTemperatura" asp-action="Temperatura">Temperatura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="TelaTemperatura" asp-action="Ph">Ph</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="ValoresSensor" asp-action="Index">Lista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Grafico" asp-action="Grafico">DashBoard Grafico</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top  bg-dark footer text-muted">
        <div class="container">
            &copy; 2024 - SiteAquario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/fontawesome.min.js"></script>  
    <script src="~/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>